twitter:
  api_key: ${API_KEY}
  api_secret_key: ${API_SECRET}
  access_token: ${TOKEN}
  access_token_secret: ${TOKEN_SECRET}

spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: none
    show-sql: true
